//
// TSVolumetricROIImporter.m
// TotalSegmentator
//

#import "TSVolumetricROIImporter.h"
#import <Cocoa/Cocoa.h>

#if __has_include(<Horos/ViewerController.h>)
#import <Horos/ViewerController.h>
#import <Horos/DCMPix.h>
#import <Horos/ROI.h>
#elif __has_include(<OsiriXAPI/ViewerController.h>)
#import <OsiriXAPI/ViewerController.h>
#import <OsiriXAPI/DCMPix.h>
#import <OsiriXAPI/ROI.h>
#else
#import "ViewerController.h"
#import "DCMPix.h"
#import "ROI.h"
#endif

static NSString * const TSVolumetricROIImporterGeneratedComment = @"Generated by TotalSegmentator volumetric ROI importer";
static const CGFloat TSVolumetricROIImporterDisplayOpacity = 0.30;

@implementation TSVolumetricROIImporter

+ (NSDictionary<NSString *, id> *)importVolumetricROIsFromManifest:(NSString *)manifestPath intoViewer:(ViewerController *)viewer {
    NSMutableDictionary<NSString *, id> *summary = [@{
        @"roi_count": @0,
        @"label_count": @0,
        @"slice_count": @0,
        @"skipped_slice_count": @0,
        @"replaced_roi_count": @0
    } mutableCopy];

    if (manifestPath.length == 0 || viewer == nil) {
        summary[@"error"] = @"Missing manifest path or viewer.";
        return summary;
    }

    NSData *jsonData = [NSData dataWithContentsOfFile:manifestPath];
    if (jsonData == nil) {
        summary[@"error"] = [NSString stringWithFormat:@"Unable to read volumetric ROI manifest at %@.", manifestPath];
        return summary;
    }

    NSError *jsonError = nil;
    id jsonObject = [NSJSONSerialization JSONObjectWithData:jsonData options:0 error:&jsonError];
    if (![jsonObject isKindOfClass:[NSDictionary class]]) {
        summary[@"error"] = jsonError.localizedDescription ?: @"Invalid volumetric ROI manifest.";
        return summary;
    }

    NSDictionary *manifest = (NSDictionary *)jsonObject;
    NSArray *labels = [self arrayValue:manifest[@"labels"]];
    if (labels.count == 0) {
        summary[@"error"] = @"The volumetric ROI manifest does not contain any labels.";
        return summary;
    }

    NSMutableArray *roiSeriesList = nil;
    if ([viewer respondsToSelector:@selector(roiList)]) {
        roiSeriesList = [viewer roiList];
    }

    NSMutableArray *pixList = nil;
    if ([viewer respondsToSelector:@selector(pixList)]) {
        pixList = [viewer pixList];
    }

    if (roiSeriesList.count == 0 || pixList.count == 0) {
        summary[@"error"] = @"The active viewer does not expose image or ROI lists.";
        return summary;
    }

    NSInteger manifestRows = [self integerFromObject:manifest[@"rows"] defaultValue:0];
    NSInteger manifestColumns = [self integerFromObject:manifest[@"columns"] defaultValue:0];
    NSDictionary<NSString *, NSNumber *> *uidToViewerIndex = [self sopInstanceUIDToViewerIndexMapForViewer:viewer];

    NSUInteger importedROICount = 0;
    NSUInteger importedLabelCount = 0;
    NSUInteger importedSliceCount = 0;
    NSUInteger skippedSliceCount = 0;
    NSUInteger replacedROICount = 0;

    NSUInteger labelOrdinal = 0;
    for (id labelObject in labels) {
        if (![labelObject isKindOfClass:[NSDictionary class]]) {
            continue;
        }

        NSDictionary *label = (NSDictionary *)labelObject;
        NSString *labelName = [self stringFromObject:label[@"name"]];
        if (labelName.length == 0) {
            labelName = [NSString stringWithFormat:@"TotalSegmentator_%lu", (unsigned long)(labelOrdinal + 1)];
        }

        NSArray *slices = [self arrayValue:label[@"slices"]];
        if (slices.count == 0) {
            labelOrdinal += 1;
            continue;
        }

        NSInteger labelIndex = [self integerFromObject:label[@"index"] defaultValue:(NSInteger)(labelOrdinal + 1)];
        NSColor *labelColor = [self colorForLabelIndex:labelIndex name:labelName];
        NSUInteger labelROICount = 0;
        NSTimeInterval groupID = [NSDate timeIntervalSinceReferenceDate] + ((NSTimeInterval)labelOrdinal / 1000.0);

        for (id sliceObject in slices) {
            if (![sliceObject isKindOfClass:[NSDictionary class]]) {
                skippedSliceCount += 1;
                continue;
            }

            NSDictionary *slice = (NSDictionary *)sliceObject;
            NSInteger sliceIndex = [self viewerSliceIndexForSlice:slice uidMap:uidToViewerIndex fallbackCount:roiSeriesList.count];
            if (sliceIndex < 0 || sliceIndex >= (NSInteger)roiSeriesList.count || sliceIndex >= (NSInteger)pixList.count) {
                skippedSliceCount += 1;
                continue;
            }

            NSString *rawPath = [self stringFromObject:slice[@"raw_path"]];
            if (rawPath.length == 0) {
                skippedSliceCount += 1;
                continue;
            }

            NSMutableData *textureData = [NSMutableData dataWithContentsOfFile:rawPath];
            if (textureData.length == 0) {
                skippedSliceCount += 1;
                continue;
            }

            NSInteger rows = [self integerFromObject:slice[@"rows"] defaultValue:manifestRows];
            NSInteger columns = [self integerFromObject:slice[@"columns"] defaultValue:manifestColumns];
            if (rows <= 0 || columns <= 0 || textureData.length != (NSUInteger)(rows * columns)) {
                skippedSliceCount += 1;
                continue;
            }

            DCMPix *pix = nil;
            id pixCandidate = pixList[(NSUInteger)sliceIndex];
            if ([pixCandidate isKindOfClass:[DCMPix class]]) {
                pix = (DCMPix *)pixCandidate;
            }
            if (pix == nil) {
                skippedSliceCount += 1;
                continue;
            }

            id roiSliceListObject = roiSeriesList[(NSUInteger)sliceIndex];
            if (![roiSliceListObject isKindOfClass:[NSMutableArray class]]) {
                skippedSliceCount += 1;
                continue;
            }

            NSMutableArray *roiSliceList = (NSMutableArray *)roiSliceListObject;
            replacedROICount += [self removeGeneratedROIsNamed:labelName fromSliceList:roiSliceList];

            ROI *roi = [[ROI alloc] initWithTexture:(unsigned char *)textureData.mutableBytes
                                          textWidth:(int)columns
                                         textHeight:(int)rows
                                           textName:labelName
                                          positionX:0
                                          positionY:0
                                           spacingX:(float)pix.pixelSpacingX
                                           spacingY:(float)pix.pixelSpacingY
                                        imageOrigin:NSMakePoint(pix.originX, pix.originY)];
            if (roi == nil) {
                skippedSliceCount += 1;
                continue;
            }

            [self setValue:pix forKey:@"pix" forROI:roi];
            [self setValue:@(pix.sliceThickness) forKey:@"sliceThickness" forROI:roi];
            [self setOpacity:TSVolumetricROIImporterDisplayOpacity forROI:roi];
            [self setValue:TSVolumetricROIImporterGeneratedComment forKey:@"comments" forROI:roi];
            [self setGroupID:groupID forROI:roi];
            [self setColor:labelColor forROI:roi];

            [roiSliceList addObject:roi];

            importedROICount += 1;
            labelROICount += 1;
            importedSliceCount += 1;
        }

        if (labelROICount > 0) {
            importedLabelCount += 1;
        }
        labelOrdinal += 1;
    }

    if ([viewer respondsToSelector:@selector(needsDisplayUpdate)]) {
        [viewer needsDisplayUpdate];
    }

    summary[@"roi_count"] = @(importedROICount);
    summary[@"label_count"] = @(importedLabelCount);
    summary[@"slice_count"] = @(importedSliceCount);
    summary[@"skipped_slice_count"] = @(skippedSliceCount);
    summary[@"replaced_roi_count"] = @(replacedROICount);

    if (importedROICount == 0 && summary[@"error"] == nil) {
        summary[@"error"] = @"No volumetric ROIs could be created from the manifest.";
    }

    return summary;
}

+ (NSArray *)arrayValue:(id)object {
    if ([object isKindOfClass:[NSArray class]]) {
        return object;
    }
    return @[];
}

+ (NSString *)stringFromObject:(id)object {
    if ([object isKindOfClass:[NSString class]]) {
        return object;
    }
    if ([object respondsToSelector:@selector(stringValue)]) {
        return [object stringValue];
    }
    return nil;
}

+ (NSInteger)integerFromObject:(id)object defaultValue:(NSInteger)defaultValue {
    if ([object respondsToSelector:@selector(integerValue)]) {
        return [object integerValue];
    }
    return defaultValue;
}

+ (NSString *)safeValueForKey:(NSString *)key fromObject:(id)object {
    if (object == nil || key.length == 0) {
        return nil;
    }

    @try {
        id value = [object valueForKey:key];
        return [self stringFromObject:value];
    } @catch (__unused NSException *exception) {
        return nil;
    }
}

+ (NSDictionary<NSString *, NSNumber *> *)sopInstanceUIDToViewerIndexMapForViewer:(ViewerController *)viewer {
    NSMutableDictionary<NSString *, NSNumber *> *map = [NSMutableDictionary dictionary];
    NSArray *fileList = nil;

    if ([viewer respondsToSelector:@selector(fileList)]) {
        fileList = [viewer fileList];
    }

    if (fileList.count == 0 && [viewer respondsToSelector:@selector(fileList:)]) {
        fileList = [viewer fileList:0];
    }

    NSArray<NSString *> *uidKeys = @[
        @"sopInstanceUID",
        @"SOPInstanceUID",
        @"sopInstanceUid",
        @"referencedSOPInstanceUID"
    ];

    [fileList enumerateObjectsUsingBlock:^(id object, NSUInteger index, BOOL *stop) {
        for (NSString *key in uidKeys) {
            NSString *uid = [self safeValueForKey:key fromObject:object];
            if (uid.length > 0) {
                map[uid] = @(index);
                break;
            }
        }
    }];

    return map;
}

+ (NSInteger)viewerSliceIndexForSlice:(NSDictionary *)slice uidMap:(NSDictionary<NSString *, NSNumber *> *)uidMap fallbackCount:(NSUInteger)fallbackCount {
    NSString *uid = [self stringFromObject:slice[@"sop_instance_uid"]];
    NSNumber *mappedIndex = uid.length > 0 ? uidMap[uid] : nil;
    if (mappedIndex != nil) {
        return mappedIndex.integerValue;
    }

    NSInteger index = [self integerFromObject:slice[@"slice_index"] defaultValue:-1];
    if (index >= 0 && index < (NSInteger)fallbackCount) {
        return index;
    }

    return -1;
}

+ (NSUInteger)removeGeneratedROIsNamed:(NSString *)labelName fromSliceList:(NSMutableArray *)roiSliceList {
    if (labelName.length == 0 || roiSliceList.count == 0) {
        return 0;
    }

    NSIndexSet *matchingIndexes = [roiSliceList indexesOfObjectsPassingTest:^BOOL(id object, NSUInteger index, BOOL *stop) {
        if (![object isKindOfClass:[ROI class]]) {
            return NO;
        }

        ROI *roi = (ROI *)object;
        NSString *roiName = [self safeValueForKey:@"name" fromObject:roi];
        NSString *comments = [self safeValueForKey:@"comments" fromObject:roi];
        return [roiName isEqualToString:labelName] && [comments isEqualToString:TSVolumetricROIImporterGeneratedComment];
    }];

    NSUInteger count = matchingIndexes.count;
    if (count > 0) {
        [roiSliceList removeObjectsAtIndexes:matchingIndexes];
    }
    return count;
}

+ (void)setValue:(id)value forKey:(NSString *)key forROI:(ROI *)roi {
    if (roi == nil || key.length == 0 || value == nil) {
        return;
    }

    @try {
        [roi setValue:value forKey:key];
    } @catch (__unused NSException *exception) {
        // Older Horos/OsiriX API headers do not expose every metadata field.
    }
}

+ (void)setGroupID:(NSTimeInterval)groupID forROI:(ROI *)roi {
    [self setValue:@(groupID) forKey:@"groupID" forROI:roi];
}

+ (NSColor *)colorForLabelIndex:(NSInteger)labelIndex name:(NSString *)labelName {
    static NSArray<NSArray<NSNumber *> *> *palette = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        palette = @[
            @[@230, @25, @75],
            @[@60, @180, @75],
            @[@255, @225, @25],
            @[@67, @99, @216],
            @[@245, @130, @49],
            @[@145, @30, @180],
            @[@70, @240, @240],
            @[@240, @50, @230],
            @[@188, @246, @12],
            @[@250, @190, @212],
            @[@0, @128, @128],
            @[@220, @190, @255],
            @[@154, @99, @36],
            @[@255, @250, @200],
            @[@128, @0, @0],
            @[@170, @255, @195],
            @[@128, @128, @0],
            @[@255, @216, @177],
            @[@0, @0, @117],
            @[@128, @128, @128]
        ];
    });

    if (labelIndex >= 1 && labelIndex <= (NSInteger)palette.count) {
        NSArray<NSNumber *> *rgb = palette[(NSUInteger)(labelIndex - 1)];
        return [NSColor colorWithCalibratedRed:rgb[0].doubleValue / 255.0
                                         green:rgb[1].doubleValue / 255.0
                                          blue:rgb[2].doubleValue / 255.0
                                         alpha:1.0];
    }

    NSString *seed = [NSString stringWithFormat:@"%ld:%@", (long)labelIndex, labelName ?: @""];
    uint32_t hash = [self stableHashForString:seed];
    CGFloat hue = (CGFloat)(hash % 360) / 360.0;
    CGFloat saturation = 0.65 + (CGFloat)((hash >> 9) % 25) / 100.0;
    CGFloat brightness = 0.82 + (CGFloat)((hash >> 17) % 15) / 100.0;
    return [NSColor colorWithCalibratedHue:hue saturation:saturation brightness:brightness alpha:1.0];
}

+ (uint32_t)stableHashForString:(NSString *)string {
    const char *bytes = string.UTF8String;
    uint32_t hash = 2166136261u;
    while (*bytes != '\0') {
        hash ^= (uint8_t)*bytes;
        hash *= 16777619u;
        bytes += 1;
    }
    return hash;
}

+ (void)setColor:(NSColor *)color forROI:(ROI *)roi {
    if (roi == nil || color == nil) {
        return;
    }

    if ([roi respondsToSelector:@selector(setNSColor:globally:)]) {
        [roi setNSColor:color globally:NO];
        return;
    }

    [self setValue:color forKey:@"NSColor" forROI:roi];
}

+ (void)setOpacity:(CGFloat)opacity forROI:(ROI *)roi {
    if (roi == nil) {
        return;
    }

    if ([roi respondsToSelector:@selector(setOpacity:globally:)]) {
        [roi setOpacity:(float)opacity globally:NO];
        return;
    }

    [self setValue:@(opacity) forKey:@"opacity" forROI:roi];
}

@end
