//
// TSVolumetricROIImporter.m
// TotalSegmentator
//

#import "TSVolumetricROIImporter.h"
#import <Cocoa/Cocoa.h>

#if __has_include(<Horos/ViewerController.h>)
#import <Horos/ViewerController.h>
#import <Horos/DCMPix.h>
#import <Horos/DicomImage.h>
#import <Horos/DicomSeries.h>
#import <Horos/Notifications.h>
#import <Horos/ROI.h>
#elif __has_include(<OsiriXAPI/ViewerController.h>)
#import <OsiriXAPI/ViewerController.h>
#import <OsiriXAPI/DCMPix.h>
#import <OsiriXAPI/DicomImage.h>
#import <OsiriXAPI/DicomSeries.h>
#import <OsiriXAPI/Notifications.h>
#import <OsiriXAPI/ROI.h>
#else
#import "ViewerController.h"
#import "DCMPix.h"
#import "DicomImage.h"
#import "DicomSeries.h"
#import "Notifications.h"
#import "ROI.h"
#endif

static NSString * const TSVolumetricROIImporterGeneratedCommentPrefix = @"Generated by TotalSegmentator volumetric ROI importer";
static const CGFloat TSVolumetricROIImporterDisplayOpacity = 0.30;

@implementation TSVolumetricROIImporter

+ (NSDictionary<NSString *, id> *)importVolumetricROIsFromManifest:(NSString *)manifestPath intoViewer:(ViewerController *)viewer {
    NSMutableDictionary<NSString *, id> *summary = [@{
        @"roi_count": @0,
        @"label_count": @0,
        @"slice_count": @0,
        @"skipped_slice_count": @0,
        @"replaced_roi_count": @0
    } mutableCopy];

    if (manifestPath.length == 0 || viewer == nil) {
        summary[@"error"] = @"Missing manifest path or viewer.";
        return summary;
    }

    NSData *jsonData = [NSData dataWithContentsOfFile:manifestPath];
    if (jsonData == nil) {
        summary[@"error"] = [NSString stringWithFormat:@"Unable to read volumetric ROI manifest at %@.", manifestPath];
        return summary;
    }

    NSError *jsonError = nil;
    id jsonObject = [NSJSONSerialization JSONObjectWithData:jsonData options:0 error:&jsonError];
    if (![jsonObject isKindOfClass:[NSDictionary class]]) {
        summary[@"error"] = jsonError.localizedDescription ?: @"Invalid volumetric ROI manifest.";
        return summary;
    }

    NSDictionary *manifest = (NSDictionary *)jsonObject;
    NSArray *labels = [self arrayValue:manifest[@"labels"]];
    if (labels.count == 0) {
        summary[@"error"] = @"The volumetric ROI manifest does not contain any labels.";
        return summary;
    }

    NSMutableArray *roiSeriesList = nil;
    if ([viewer respondsToSelector:@selector(roiList)]) {
        roiSeriesList = [viewer roiList];
    }

    NSMutableArray *pixList = nil;
    if ([viewer respondsToSelector:@selector(pixList)]) {
        pixList = [viewer pixList];
    }

    if (roiSeriesList.count == 0 || pixList.count == 0) {
        summary[@"error"] = @"The active viewer does not expose image or ROI lists.";
        return summary;
    }

    NSString *roiComment = [self roiProvenanceCommentFromManifest:manifest];
    if (roiComment.length == 0) {
        summary[@"error"] = @"The volumetric ROI manifest is missing job-specific ROI provenance.";
        return summary;
    }

    NSString *identityError = nil;
    if (![self viewerIdentityMatchesManifest:manifest viewer:viewer pixList:pixList error:&identityError]) {
        summary[@"error"] = identityError ?: @"source identity mismatch: viewer does not match the segmentation source.";
        return summary;
    }

    NSInteger manifestRows = [self integerFromObject:manifest[@"rows"] defaultValue:0];
    NSInteger manifestColumns = [self integerFromObject:manifest[@"columns"] defaultValue:0];
    BOOL projectedViewerGeometry = [self isProjectedViewerGeometryManifest:manifest];
    NSDictionary<NSString *, NSNumber *> *uidToViewerIndex = projectedViewerGeometry
        ? [self projectedViewerSliceIndexMapForPixList:pixList]
        : [self sopInstanceUIDToViewerIndexMapForViewer:viewer];

    NSUInteger importedROICount = 0;
    NSUInteger importedLabelCount = 0;
    NSUInteger importedSliceCount = 0;
    NSUInteger skippedSliceCount = 0;
    NSUInteger replacedROICount = 0;

    NSUInteger labelOrdinal = 0;
    for (id labelObject in labels) {
        if (![labelObject isKindOfClass:[NSDictionary class]]) {
            continue;
        }

        NSDictionary *label = (NSDictionary *)labelObject;
        NSString *labelName = [self stringFromObject:label[@"name"]];
        if (labelName.length == 0) {
            labelName = [NSString stringWithFormat:@"TotalSegmentator_%lu", (unsigned long)(labelOrdinal + 1)];
        }

        NSArray *slices = [self arrayValue:label[@"slices"]];
        if (slices.count == 0) {
            labelOrdinal += 1;
            continue;
        }

        NSInteger labelIndex = [self integerFromObject:label[@"index"] defaultValue:(NSInteger)(labelOrdinal + 1)];
        NSColor *labelColor = [self colorForLabel:label defaultIndex:labelIndex name:labelName];
        NSUInteger labelROICount = 0;
        NSTimeInterval groupID = [NSDate timeIntervalSinceReferenceDate] + ((NSTimeInterval)labelOrdinal / 1000.0);

        for (id sliceObject in slices) {
            if (![sliceObject isKindOfClass:[NSDictionary class]]) {
                skippedSliceCount += 1;
                continue;
            }

            NSDictionary *slice = (NSDictionary *)sliceObject;
            NSInteger sliceIndex = [self viewerSliceIndexForSlice:slice uidMap:uidToViewerIndex];
            if (sliceIndex < 0 || sliceIndex >= (NSInteger)roiSeriesList.count || sliceIndex >= (NSInteger)pixList.count) {
                skippedSliceCount += 1;
                continue;
            }

            NSString *rawPath = [self stringFromObject:slice[@"raw_path"]];
            if (rawPath.length == 0) {
                skippedSliceCount += 1;
                continue;
            }

            NSMutableData *textureData = [NSMutableData dataWithContentsOfFile:rawPath];
            if (textureData.length == 0) {
                skippedSliceCount += 1;
                continue;
            }

            NSInteger rows = [self integerFromObject:slice[@"rows"] defaultValue:manifestRows];
            NSInteger columns = [self integerFromObject:slice[@"columns"] defaultValue:manifestColumns];
            if (rows <= 0 || columns <= 0 || textureData.length != (NSUInteger)(rows * columns)) {
                skippedSliceCount += 1;
                continue;
            }

            DCMPix *pix = nil;
            id pixCandidate = pixList[(NSUInteger)sliceIndex];
            if ([pixCandidate isKindOfClass:[DCMPix class]]) {
                pix = (DCMPix *)pixCandidate;
            }
            if (pix == nil) {
                skippedSliceCount += 1;
                continue;
            }

            id roiSliceListObject = roiSeriesList[(NSUInteger)sliceIndex];
            if (![roiSliceListObject isKindOfClass:[NSMutableArray class]]) {
                skippedSliceCount += 1;
                continue;
            }

            NSMutableArray *roiSliceList = (NSMutableArray *)roiSliceListObject;
            replacedROICount += [self removeGeneratedROIsNamed:labelName fromSliceList:roiSliceList roiComment:roiComment];

            ROI *roi = [[ROI alloc] initWithTexture:(unsigned char *)textureData.mutableBytes
                                          textWidth:(int)columns
                                         textHeight:(int)rows
                                           textName:labelName
                                          positionX:0
                                          positionY:0
                                           spacingX:(float)pix.pixelSpacingX
                                           spacingY:(float)pix.pixelSpacingY
                                        imageOrigin:NSMakePoint(pix.originX, pix.originY)];
            if (roi == nil) {
                skippedSliceCount += 1;
                continue;
            }

            [self setValue:pix forKey:@"pix" forROI:roi];
            [self setValue:@(pix.sliceThickness) forKey:@"sliceThickness" forROI:roi];
            [self setOpacity:TSVolumetricROIImporterDisplayOpacity forROI:roi];
            [self setValue:roiComment forKey:@"comments" forROI:roi];
            [self setGroupID:groupID forROI:roi];
            [self setColor:labelColor forROI:roi];
            [self setValue:@YES forKey:@"textNameOnly" forROI:roi];
            [self setValue:@YES forKey:@"locked" forROI:roi];
            [self setValue:@NO forKey:@"hidden" forROI:roi];

            [self reduceTextureIfPossibleForROI:roi];
            if (![self isValidBrushROI:roi]) {
                skippedSliceCount += 1;
                continue;
            }

            [roiSliceList addObject:roi];

            importedROICount += 1;
            labelROICount += 1;
            importedSliceCount += 1;
        }

        if (labelROICount > 0) {
            importedLabelCount += 1;
        }
        labelOrdinal += 1;
    }

    if (importedROICount > 0) {
        [self mergeBrushROIsWithSameNameIfAvailableForViewer:viewer];
        [self postROIChangeNotification];
    }

    if ([viewer respondsToSelector:@selector(needsDisplayUpdate)]) {
        [viewer needsDisplayUpdate];
    }

    summary[@"roi_count"] = @(importedROICount);
    summary[@"label_count"] = @(importedLabelCount);
    summary[@"slice_count"] = @(importedSliceCount);
    summary[@"skipped_slice_count"] = @(skippedSliceCount);
    summary[@"replaced_roi_count"] = @(replacedROICount);

    if (importedROICount == 0 && summary[@"error"] == nil) {
        summary[@"error"] = @"No volumetric ROIs could be created from the manifest.";
    }

    return summary;
}

+ (NSArray *)arrayValue:(id)object {
    if ([object isKindOfClass:[NSArray class]]) {
        return object;
    }
    return @[];
}

+ (NSString *)stringFromObject:(id)object {
    if ([object isKindOfClass:[NSString class]]) {
        return object;
    }
    if ([object respondsToSelector:@selector(stringValue)]) {
        return [object stringValue];
    }
    return nil;
}

+ (NSInteger)integerFromObject:(id)object defaultValue:(NSInteger)defaultValue {
    if ([object respondsToSelector:@selector(integerValue)]) {
        return [object integerValue];
    }
    return defaultValue;
}

+ (BOOL)boolFromObject:(id)object {
    if ([object respondsToSelector:@selector(boolValue)]) {
        return [object boolValue];
    }
    return NO;
}

+ (NSString *)safeValueForKey:(NSString *)key fromObject:(id)object {
    if (object == nil || key.length == 0) {
        return nil;
    }
    if ([self isDicomImageObject:object]) {
        return nil;
    }

    @try {
        id value = [object valueForKey:key];
        return [self stringFromObject:value];
    } @catch (__unused NSException *exception) {
        return nil;
    }
}

+ (NSString *)normalizedStringFromObject:(id)object {
    NSString *value = [self stringFromObject:object];
    value = [value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
    return value.length > 0 ? value : nil;
}

+ (NSString *)roiProvenanceCommentFromManifest:(NSDictionary *)manifest {
    NSString *comment = [self normalizedStringFromObject:manifest[@"roi_provenance_comment"]];
    if (comment.length > 0) {
        return comment;
    }

    NSString *jobUUID = [self normalizedStringFromObject:manifest[@"job_uuid"]];
    NSString *sourceIdentityHash = [self normalizedStringFromObject:manifest[@"source_identity_hash"]];
    if (jobUUID.length == 0 || sourceIdentityHash.length == 0) {
        return nil;
    }

    return [NSString stringWithFormat:@"%@; job=%@; source=%@",
            TSVolumetricROIImporterGeneratedCommentPrefix,
            jobUUID,
            sourceIdentityHash];
}

+ (BOOL)viewerIdentityMatchesManifest:(NSDictionary *)manifest
                                viewer:(ViewerController *)viewer
                               pixList:(NSArray *)pixList
                                 error:(NSString **)error {
    NSDictionary *sourceIdentity = [manifest[@"source_identity"] isKindOfClass:[NSDictionary class]] ? manifest[@"source_identity"] : nil;
    if (sourceIdentity == nil) {
        if (error != nil) {
            *error = @"source identity mismatch: manifest missing source_identity.";
        }
        return NO;
    }

    if ([self isProjectedViewerGeometryManifest:manifest]) {
        return [self viewerGeometryMatchesProjectedManifest:manifest pixList:pixList error:error];
    }

    NSArray *expectedSOPs = [self arrayValue:sourceIdentity[@"ordered_sop_instance_uids"]];
    if (expectedSOPs.count == 0) {
        if (error != nil) {
            *error = @"source identity mismatch: manifest has no ordered SOP Instance UIDs.";
        }
        return NO;
    }

    NSDictionary<NSString *, NSNumber *> *uidToViewerIndex = [self sopInstanceUIDToViewerIndexMapForViewer:viewer];
    if (uidToViewerIndex.count == 0) {
        if (error != nil) {
            *error = @"source identity mismatch: viewer exposes no SOP Instance UIDs.";
        }
        return NO;
    }

    NSSet *expectedSet = [NSSet setWithArray:expectedSOPs];
    NSSet *actualSet = [NSSet setWithArray:uidToViewerIndex.allKeys];
    NSUInteger viewerSOPCount = [self viewerSOPInstanceUIDCountForViewer:viewer];
    if (![expectedSet isEqualToSet:actualSet] || expectedSet.count != expectedSOPs.count || actualSet.count != viewerSOPCount) {
        if (error != nil) {
            *error = @"source identity mismatch: viewer SOP Instance UIDs differ from the segmentation source.";
        }
        return NO;
    }

    NSString *expectedStudyUID = [self normalizedStringFromObject:sourceIdentity[@"study_instance_uid"]];
    if (expectedStudyUID.length > 0) {
        NSString *viewerStudyUID = nil;
        if ([viewer respondsToSelector:@selector(studyInstanceUID)]) {
            viewerStudyUID = [self normalizedStringFromObject:[viewer studyInstanceUID]];
        }
        if (viewerStudyUID.length > 0 && ![viewerStudyUID isEqualToString:expectedStudyUID]) {
            if (error != nil) {
                *error = @"source identity mismatch: Study Instance UID differs.";
            }
            return NO;
        }
    }

    NSString *expectedSeriesUID = [self normalizedStringFromObject:sourceIdentity[@"series_instance_uid"]];
    if (expectedSeriesUID.length > 0 && ![self viewer:viewer hasSeriesInstanceUID:expectedSeriesUID]) {
        if (error != nil) {
            *error = @"source identity mismatch: Series Instance UID differs.";
        }
        return NO;
    }

    NSString *expectedFrameUID = [self normalizedStringFromObject:sourceIdentity[@"frame_of_reference_uid"]];
    if (expectedFrameUID.length > 0 && ![self pixList:pixList hasFrameOfReferenceUID:expectedFrameUID]) {
        if (error != nil) {
            *error = @"source identity mismatch: Frame of Reference UID differs.";
        }
        return NO;
    }

    NSInteger manifestRows = [self integerFromObject:manifest[@"rows"] defaultValue:0];
    NSInteger manifestColumns = [self integerFromObject:manifest[@"columns"] defaultValue:0];
    if (manifestRows > 0 && manifestColumns > 0 && ![self pixList:pixList matchesRows:manifestRows columns:manifestColumns]) {
        if (error != nil) {
            *error = @"source geometry mismatch: viewer dimensions differ from the segmentation source.";
        }
        return NO;
    }

    return YES;
}

+ (BOOL)viewer:(ViewerController *)viewer hasSeriesInstanceUID:(NSString *)expectedSeriesUID {
    NSArray *fileList = nil;
    if ([viewer respondsToSelector:@selector(fileList)]) {
        fileList = [viewer fileList];
    }
    if (fileList.count == 0 && [viewer respondsToSelector:@selector(fileList:)]) {
        fileList = [viewer fileList:0];
    }

    BOOL foundExpectedSeriesUID = NO;
    for (id object in fileList) {
        NSString *seriesUID = [self seriesInstanceUIDFromObject:object];
        if (seriesUID.length == 0) {
            continue;
        }
        if (![seriesUID isEqualToString:expectedSeriesUID]) {
            return NO;
        }
        foundExpectedSeriesUID = YES;
    }

    return foundExpectedSeriesUID;
}

+ (BOOL)isDicomImageObject:(id)object {
    Class dicomImageClass = NSClassFromString(@"DicomImage");
    return dicomImageClass != Nil && [object isKindOfClass:dicomImageClass];
}

+ (id)objectValueByCallingSelector:(SEL)selector fromObject:(id)object {
    if (object == nil || selector == NULL || ![object respondsToSelector:selector]) {
        return nil;
    }
    IMP implementation = [object methodForSelector:selector];
    id (*function)(id, SEL) = (void *)implementation;
    return function(object, selector);
}

+ (NSString *)stringValueByCallingSelector:(SEL)selector fromObject:(id)object {
    return [self normalizedStringFromObject:[self objectValueByCallingSelector:selector fromObject:object]];
}

+ (NSString *)sopInstanceUIDFromObject:(id)object {
    NSString *uid = [self stringValueByCallingSelector:@selector(sopInstanceUID) fromObject:object];
    if (uid.length > 0) {
        return uid;
    }

    uid = [self stringValueByCallingSelector:@selector(UID) fromObject:object];
    if (uid.length > 0) {
        return uid;
    }

    if ([self isDicomImageObject:object]) {
        return nil;
    }

    NSArray<NSString *> *uidKeys = @[
        @"sopInstanceUID",
        @"SOPInstanceUID",
        @"sopInstanceUid",
        @"referencedSOPInstanceUID"
    ];
    for (NSString *key in uidKeys) {
        uid = [self safeValueForKey:key fromObject:object];
        if (uid.length > 0) {
            return uid;
        }
    }
    return nil;
}

+ (NSString *)seriesInstanceUIDFromObject:(id)object {
    NSString *uid = [self stringValueByCallingSelector:@selector(seriesInstanceUID) fromObject:object];
    if (uid.length > 0) {
        return uid;
    }

    id series = [self objectValueByCallingSelector:@selector(series) fromObject:object];
    uid = [self stringValueByCallingSelector:@selector(seriesInstanceUID) fromObject:series];
    if (uid.length > 0) {
        return uid;
    }

    if ([self isDicomImageObject:object]) {
        return nil;
    }

    for (NSString *key in @[@"seriesInstanceUID", @"SeriesInstanceUID", @"seriesDICOMUID"]) {
        uid = [self safeValueForKey:key fromObject:object];
        if (uid.length > 0) {
            return uid;
        }
    }
    return nil;
}

+ (BOOL)pixList:(NSArray *)pixList hasFrameOfReferenceUID:(NSString *)expectedFrameUID {
    BOOL foundFrameUID = NO;
    for (id object in pixList) {
        NSString *frameUID = [self safeValueForKey:@"frameofReferenceUID" fromObject:object];
        if (frameUID.length == 0) {
            continue;
        }
        foundFrameUID = YES;
        if (![frameUID isEqualToString:expectedFrameUID]) {
            return NO;
        }
    }
    return foundFrameUID;
}

+ (BOOL)pixList:(NSArray *)pixList matchesRows:(NSInteger)rows columns:(NSInteger)columns {
    for (id object in pixList) {
        NSInteger pixRows = [self integerFromObject:[self safeValueForKey:@"pheight" fromObject:object] defaultValue:0];
        NSInteger pixColumns = [self integerFromObject:[self safeValueForKey:@"pwidth" fromObject:object] defaultValue:0];
        if (pixRows > 0 && pixRows != rows) {
            return NO;
        }
        if (pixColumns > 0 && pixColumns != columns) {
            return NO;
        }
    }
    return YES;
}

+ (BOOL)isProjectedViewerGeometryManifest:(NSDictionary *)manifest {
    return [self boolFromObject:manifest[@"viewer_geometry_projection"]];
}

+ (BOOL)viewerGeometryMatchesProjectedManifest:(NSDictionary *)manifest
                                       pixList:(NSArray *)pixList
                                         error:(NSString **)error {
    NSArray *labels = [self arrayValue:manifest[@"labels"]];
    if (labels.count == 0 || pixList.count == 0) {
        if (error != nil) {
            *error = @"projected viewer geometry mismatch: manifest or viewer has no slices.";
        }
        return NO;
    }

    BOOL foundProjectedSlice = NO;
    for (id labelObject in labels) {
        if (![labelObject isKindOfClass:[NSDictionary class]]) {
            continue;
        }

        NSArray *slices = [self arrayValue:((NSDictionary *)labelObject)[@"slices"]];
        for (id sliceObject in slices) {
            if (![sliceObject isKindOfClass:[NSDictionary class]]) {
                continue;
            }

            NSDictionary *slice = (NSDictionary *)sliceObject;
            NSInteger sliceIndex = [self integerFromObject:slice[@"slice_index"] defaultValue:-1];
            if (sliceIndex < 0 || sliceIndex >= (NSInteger)pixList.count) {
                if (error != nil) {
                    *error = @"projected viewer geometry mismatch: slice index is outside the viewer.";
                }
                return NO;
            }

            NSString *uid = [self stringFromObject:slice[@"sop_instance_uid"]];
            NSString *expectedUID = [NSString stringWithFormat:@"viewer_slice_%ld", (long)sliceIndex];
            if (![uid isEqualToString:expectedUID]) {
                if (error != nil) {
                    *error = @"projected viewer geometry mismatch: slice UID is not a viewer geometry UID.";
                }
                return NO;
            }

            id pix = pixList[(NSUInteger)sliceIndex];
            NSInteger rows = [self integerFromObject:slice[@"rows"] defaultValue:0];
            NSInteger columns = [self integerFromObject:slice[@"columns"] defaultValue:0];
            NSInteger pixRows = [self integerFromObject:[self safeValueForKey:@"pheight" fromObject:pix] defaultValue:0];
            NSInteger pixColumns = [self integerFromObject:[self safeValueForKey:@"pwidth" fromObject:pix] defaultValue:0];
            if ((rows > 0 && pixRows > 0 && rows != pixRows) ||
                (columns > 0 && pixColumns > 0 && columns != pixColumns)) {
                if (error != nil) {
                    *error = @"projected viewer geometry mismatch: slice dimensions differ from the viewer.";
                }
                return NO;
            }
            foundProjectedSlice = YES;
        }
    }

    if (!foundProjectedSlice && error != nil) {
        *error = @"projected viewer geometry mismatch: manifest has no projected ROI slices.";
    }
    return foundProjectedSlice;
}

+ (NSDictionary<NSString *, NSNumber *> *)sopInstanceUIDToViewerIndexMapForViewer:(ViewerController *)viewer {
    NSMutableDictionary<NSString *, NSNumber *> *map = [NSMutableDictionary dictionary];
    NSArray *fileList = nil;

    if ([viewer respondsToSelector:@selector(fileList)]) {
        fileList = [viewer fileList];
    }

    if (fileList.count == 0 && [viewer respondsToSelector:@selector(fileList:)]) {
        fileList = [viewer fileList:0];
    }

    [fileList enumerateObjectsUsingBlock:^(id object, NSUInteger index, BOOL *stop) {
        NSString *uid = [self sopInstanceUIDFromObject:object];
        if (uid.length > 0) {
            map[uid] = @(index);
        }
    }];

    return map;
}

+ (NSDictionary<NSString *, NSNumber *> *)projectedViewerSliceIndexMapForPixList:(NSArray *)pixList {
    NSMutableDictionary<NSString *, NSNumber *> *map = [NSMutableDictionary dictionary];
    for (NSUInteger index = 0; index < pixList.count; index++) {
        map[[NSString stringWithFormat:@"viewer_slice_%lu", (unsigned long)index]] = @(index);
    }
    return map;
}

+ (NSUInteger)viewerSOPInstanceUIDCountForViewer:(ViewerController *)viewer {
    NSArray *fileList = nil;

    if ([viewer respondsToSelector:@selector(fileList)]) {
        fileList = [viewer fileList];
    }

    if (fileList.count == 0 && [viewer respondsToSelector:@selector(fileList:)]) {
        fileList = [viewer fileList:0];
    }

    __block NSUInteger uidCount = 0;
    [fileList enumerateObjectsUsingBlock:^(id object, NSUInteger index, BOOL *stop) {
        NSString *uid = [self sopInstanceUIDFromObject:object];
        if (uid.length > 0) {
            uidCount += 1;
        }
    }];

    return uidCount;
}

+ (NSInteger)viewerSliceIndexForSlice:(NSDictionary *)slice uidMap:(NSDictionary<NSString *, NSNumber *> *)uidMap {
    NSString *uid = [self stringFromObject:slice[@"sop_instance_uid"]];
    NSNumber *mappedIndex = uid.length > 0 ? uidMap[uid] : nil;
    if (mappedIndex != nil) {
        return mappedIndex.integerValue;
    }

    return -1;
}

+ (NSUInteger)removeGeneratedROIsNamed:(NSString *)labelName fromSliceList:(NSMutableArray *)roiSliceList roiComment:(NSString *)roiComment {
    if (labelName.length == 0 || roiSliceList.count == 0 || roiComment.length == 0) {
        return 0;
    }

    NSIndexSet *matchingIndexes = [roiSliceList indexesOfObjectsPassingTest:^BOOL(id object, NSUInteger index, BOOL *stop) {
        if (![object isKindOfClass:[ROI class]]) {
            return NO;
        }

        ROI *roi = (ROI *)object;
        NSString *roiName = [self safeValueForKey:@"name" fromObject:roi];
        NSString *comments = [self safeValueForKey:@"comments" fromObject:roi];
        return [roiName isEqualToString:labelName] && [comments isEqualToString:roiComment];
    }];

    NSUInteger count = matchingIndexes.count;
    if (count > 0) {
        [roiSliceList removeObjectsAtIndexes:matchingIndexes];
    }
    return count;
}

+ (void)setValue:(id)value forKey:(NSString *)key forROI:(ROI *)roi {
    if (roi == nil || key.length == 0 || value == nil) {
        return;
    }

    @try {
        [roi setValue:value forKey:key];
    } @catch (__unused NSException *exception) {
        // Older Horos/OsiriX API headers do not expose every metadata field.
    }
}

+ (void)setGroupID:(NSTimeInterval)groupID forROI:(ROI *)roi {
    [self setValue:@(groupID) forKey:@"groupID" forROI:roi];
}

+ (NSColor *)colorForLabelIndex:(NSInteger)labelIndex name:(NSString *)labelName {
    static NSArray<NSArray<NSNumber *> *> *palette = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        palette = @[
            @[@230, @25, @75],
            @[@60, @180, @75],
            @[@255, @225, @25],
            @[@67, @99, @216],
            @[@245, @130, @49],
            @[@145, @30, @180],
            @[@70, @240, @240],
            @[@240, @50, @230],
            @[@188, @246, @12],
            @[@250, @190, @212],
            @[@0, @128, @128],
            @[@220, @190, @255],
            @[@154, @99, @36],
            @[@255, @250, @200],
            @[@128, @0, @0],
            @[@170, @255, @195],
            @[@128, @128, @0],
            @[@255, @216, @177],
            @[@0, @0, @117],
            @[@128, @128, @128]
        ];
    });

    if (labelIndex >= 1 && labelIndex <= (NSInteger)palette.count) {
        NSArray<NSNumber *> *rgb = palette[(NSUInteger)(labelIndex - 1)];
        return [NSColor colorWithCalibratedRed:rgb[0].doubleValue / 255.0
                                         green:rgb[1].doubleValue / 255.0
                                          blue:rgb[2].doubleValue / 255.0
                                         alpha:1.0];
    }

    NSString *seed = [NSString stringWithFormat:@"%ld:%@", (long)labelIndex, labelName ?: @""];
    uint32_t hash = [self stableHashForString:seed];
    CGFloat hue = (CGFloat)(hash % 360) / 360.0;
    CGFloat saturation = 0.65 + (CGFloat)((hash >> 9) % 25) / 100.0;
    CGFloat brightness = 0.82 + (CGFloat)((hash >> 17) % 15) / 100.0;
    return [NSColor colorWithCalibratedHue:hue saturation:saturation brightness:brightness alpha:1.0];
}

+ (NSColor *)colorForLabel:(NSDictionary *)label defaultIndex:(NSInteger)labelIndex name:(NSString *)labelName {
    NSArray *rgb = [self arrayValue:label[@"display_color"]];
    if (rgb.count == 3) {
        NSInteger red = [self integerFromObject:rgb[0] defaultValue:-1];
        NSInteger green = [self integerFromObject:rgb[1] defaultValue:-1];
        NSInteger blue = [self integerFromObject:rgb[2] defaultValue:-1];
        if (red >= 0 && red <= 255 && green >= 0 && green <= 255 && blue >= 0 && blue <= 255) {
            return [NSColor colorWithCalibratedRed:(CGFloat)red / 255.0
                                            green:(CGFloat)green / 255.0
                                             blue:(CGFloat)blue / 255.0
                                            alpha:1.0];
        }
    }

    return [self colorForLabelIndex:labelIndex name:labelName];
}

+ (uint32_t)stableHashForString:(NSString *)string {
    const char *bytes = string.UTF8String;
    uint32_t hash = 2166136261u;
    while (*bytes != '\0') {
        hash ^= (uint8_t)*bytes;
        hash *= 16777619u;
        bytes += 1;
    }
    return hash;
}

+ (void)setColor:(NSColor *)color forROI:(ROI *)roi {
    if (roi == nil || color == nil) {
        return;
    }

    if ([roi respondsToSelector:@selector(setNSColor:globally:)]) {
        [roi setNSColor:color globally:NO];
        return;
    }

    [self setValue:color forKey:@"NSColor" forROI:roi];
}

+ (void)setOpacity:(CGFloat)opacity forROI:(ROI *)roi {
    if (roi == nil) {
        return;
    }

    if ([roi respondsToSelector:@selector(setOpacity:globally:)]) {
        [roi setOpacity:(float)opacity globally:NO];
        return;
    }

    [self setValue:@(opacity) forKey:@"opacity" forROI:roi];
}

+ (void)reduceTextureIfPossibleForROI:(ROI *)roi {
    if (roi == nil || ![roi respondsToSelector:@selector(reduceTextureIfPossible)]) {
        return;
    }

    IMP implementation = [roi methodForSelector:@selector(reduceTextureIfPossible)];
    BOOL (*function)(id, SEL) = (BOOL (*)(id, SEL))implementation;
    (void)function(roi, @selector(reduceTextureIfPossible));
}

+ (BOOL)isValidBrushROI:(ROI *)roi {
    if (roi == nil) {
        return NO;
    }

    for (NSString *selectorName in @[@"isValid", @"valid"]) {
        SEL selector = NSSelectorFromString(selectorName);
        if (![roi respondsToSelector:selector]) {
            continue;
        }

        IMP implementation = [roi methodForSelector:selector];
        BOOL (*function)(id, SEL) = (BOOL (*)(id, SEL))implementation;
        return function(roi, selector);
    }

    return YES;
}

+ (void)mergeBrushROIsWithSameNameIfAvailableForViewer:(ViewerController *)viewer {
    if (viewer == nil) {
        return;
    }

    SEL selector = NSSelectorFromString(@"mergeBrushROIsWithSameName:");
    if (![viewer respondsToSelector:selector]) {
        return;
    }

    IMP implementation = [viewer methodForSelector:selector];
    void (*function)(id, SEL, id) = (void (*)(id, SEL, id))implementation;
    function(viewer, selector, nil);
}

+ (void)postROIChangeNotification {
    if (OsirixROIChangeNotification.length == 0) {
        return;
    }

    [[NSNotificationCenter defaultCenter] postNotificationName:OsirixROIChangeNotification
                                                        object:nil
                                                      userInfo:nil];
}

@end
